-- -------------------------------------------------------------
-- 
-- File Name: D:\GSLAB\FPGA_LinearRegression\G01-SourceCode\codegen\linearRegression_LeastSquares\hdlsrc\linearRegression_LeastSquares_fixpt_pkg.vhd
-- Created: 2022-05-07 22:24:30
-- 
-- Generated by MATLAB 9.11, MATLAB Coder 5.3 and HDL Coder 3.19
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE linearRegression_LeastSquares_fixpt_pkg IS
  TYPE vector_of_signed46 IS ARRAY (NATURAL RANGE <>) OF signed(45 DOWNTO 0);
  TYPE vector_of_signed24 IS ARRAY (NATURAL RANGE <>) OF signed(23 DOWNTO 0);
  TYPE vector_of_signed25 IS ARRAY (NATURAL RANGE <>) OF signed(24 DOWNTO 0);
  TYPE vector_of_signed14 IS ARRAY (NATURAL RANGE <>) OF signed(13 DOWNTO 0);
END linearRegression_LeastSquares_fixpt_pkg;

